INSERT INTO `game_system`(`name`, `short_name`, `website`, `mediaId`) VALUES ('Game System 1', 'GS_1', NULL, NULL),
('Game System 2', 'GS_2', NULL, NULL),
('Game System 3', 'GS_3', NULL, NULL),
('Game System 4', 'GS_4', NULL, NULL),
('Game System 5', 'GS_5', NULL, NULL),
('Game System 6', 'GS_6', NULL, NULL),
('Game System 7', 'GS_7', NULL, NULL),
('Game System 8', 'GS_8', NULL, NULL),
('Game System 9', 'GS_9', NULL, NULL),
('Game System 10', 'GS_10', NULL, NULL);

INSERT INTO `universe`(`creation_time`, `description`, `name`, `mediaId`) VALUES (CURRENT_TIMESTAMP, 'Description univers 1', 'Univers 1', NULL),
(CURRENT_TIMESTAMP, 'Description univers 2', 'Univers 2', NULL),
(CURRENT_TIMESTAMP, 'Description univers 3', 'Univers 3', NULL),
(CURRENT_TIMESTAMP, 'Description univers 4', 'Univers 4', NULL),
(CURRENT_TIMESTAMP, 'Description univers 5', 'Univers 5', NULL),
(CURRENT_TIMESTAMP, 'Description univers 6', 'Univers 6', NULL),
(CURRENT_TIMESTAMP, 'Description univers 7', 'Univers 7', NULL),
(CURRENT_TIMESTAMP, 'Description univers 8', 'Univers 8', NULL),
(CURRENT_TIMESTAMP, 'Description univers 9', 'Univers 9', NULL),
(CURRENT_TIMESTAMP, 'Description univers 10', 'Univers 10', NULL);

INSERT INTO `portage`(`creation_time`, `game_systemId`, `universeId`) VALUES (CURRENT_TIMESTAMP, '1', '1'),
(CURRENT_TIMESTAMP, '1', '2'),
(CURRENT_TIMESTAMP, '1', '3'),
(CURRENT_TIMESTAMP, '1', '4'),
(CURRENT_TIMESTAMP, '1', '5'),
(CURRENT_TIMESTAMP, '1', '6'),
(CURRENT_TIMESTAMP, '1', '7'),
(CURRENT_TIMESTAMP, '1', '8'),
(CURRENT_TIMESTAMP, '1', '9'),
(CURRENT_TIMESTAMP, '1', '10');
INSERT INTO `portage`(`creation_time`, `game_systemId`, `universeId`) VALUES (CURRENT_TIMESTAMP, '2', '1'),
(CURRENT_TIMESTAMP, '2', '2'),
(CURRENT_TIMESTAMP, '2', '3'),
(CURRENT_TIMESTAMP, '2', '4'),
(CURRENT_TIMESTAMP, '2', '5'),
(CURRENT_TIMESTAMP, '2', '6'),
(CURRENT_TIMESTAMP, '2', '7'),
(CURRENT_TIMESTAMP, '2', '8'),
(CURRENT_TIMESTAMP, '2', '9'),
(CURRENT_TIMESTAMP, '2', '10');
INSERT INTO `portage`(`creation_time`, `game_systemId`, `universeId`) VALUES (CURRENT_TIMESTAMP, '3', '1'),
(CURRENT_TIMESTAMP, '3', '2'),
(CURRENT_TIMESTAMP, '3', '3'),
(CURRENT_TIMESTAMP, '3', '4'),
(CURRENT_TIMESTAMP, '3', '5'),
(CURRENT_TIMESTAMP, '3', '6'),
(CURRENT_TIMESTAMP, '3', '7'),
(CURRENT_TIMESTAMP, '3', '8'),
(CURRENT_TIMESTAMP, '3', '9'),
(CURRENT_TIMESTAMP, '3', '10');
INSERT INTO `portage`(`creation_time`, `game_systemId`, `universeId`) VALUES (CURRENT_TIMESTAMP, '4', '1'),
(CURRENT_TIMESTAMP, '4', '2'),
(CURRENT_TIMESTAMP, '4', '3'),
(CURRENT_TIMESTAMP, '4', '4'),
(CURRENT_TIMESTAMP, '4', '5'),
(CURRENT_TIMESTAMP, '4', '6'),
(CURRENT_TIMESTAMP, '4', '7'),
(CURRENT_TIMESTAMP, '4', '8'),
(CURRENT_TIMESTAMP, '4', '9'),
(CURRENT_TIMESTAMP, '4', '10');
INSERT INTO `portage`(`creation_time`, `game_systemId`, `universeId`) VALUES (CURRENT_TIMESTAMP, '5', '1'),
(CURRENT_TIMESTAMP, '5', '2'),
(CURRENT_TIMESTAMP, '5', '3'),
(CURRENT_TIMESTAMP, '5', '4'),
(CURRENT_TIMESTAMP, '5', '5'),
(CURRENT_TIMESTAMP, '5', '6'),
(CURRENT_TIMESTAMP, '5', '7'),
(CURRENT_TIMESTAMP, '5', '8'),
(CURRENT_TIMESTAMP, '5', '9'),
(CURRENT_TIMESTAMP, '5', '10');
INSERT INTO `portage`(`creation_time`, `game_systemId`, `universeId`) VALUES (CURRENT_TIMESTAMP, '6', '1'),
(CURRENT_TIMESTAMP, '6', '2'),
(CURRENT_TIMESTAMP, '6', '3'),
(CURRENT_TIMESTAMP, '6', '4'),
(CURRENT_TIMESTAMP, '6', '5'),
(CURRENT_TIMESTAMP, '6', '6'),
(CURRENT_TIMESTAMP, '6', '7'),
(CURRENT_TIMESTAMP, '6', '8'),
(CURRENT_TIMESTAMP, '6', '9'),
(CURRENT_TIMESTAMP, '6', '10');
INSERT INTO `portage`(`creation_time`, `game_systemId`, `universeId`) VALUES (CURRENT_TIMESTAMP, '7', '1'),
(CURRENT_TIMESTAMP, '7', '2'),
(CURRENT_TIMESTAMP, '7', '3'),
(CURRENT_TIMESTAMP, '7', '4'),
(CURRENT_TIMESTAMP, '7', '5'),
(CURRENT_TIMESTAMP, '7', '6'),
(CURRENT_TIMESTAMP, '7', '7'),
(CURRENT_TIMESTAMP, '7', '8'),
(CURRENT_TIMESTAMP, '7', '9'),
(CURRENT_TIMESTAMP, '7', '10');
INSERT INTO `portage`(`creation_time`, `game_systemId`, `universeId`) VALUES (CURRENT_TIMESTAMP, '8', '1'),
(CURRENT_TIMESTAMP, '8', '2'),
(CURRENT_TIMESTAMP, '8', '3'),
(CURRENT_TIMESTAMP, '8', '4'),
(CURRENT_TIMESTAMP, '8', '5'),
(CURRENT_TIMESTAMP, '8', '6'),
(CURRENT_TIMESTAMP, '8', '7'),
(CURRENT_TIMESTAMP, '8', '8'),
(CURRENT_TIMESTAMP, '8', '9'),
(CURRENT_TIMESTAMP, '8', '10');
INSERT INTO `portage`(`creation_time`, `game_systemId`, `universeId`) VALUES (CURRENT_TIMESTAMP, '9', '1'),
(CURRENT_TIMESTAMP, '9', '2'),
(CURRENT_TIMESTAMP, '9', '3'),
(CURRENT_TIMESTAMP, '9', '4'),
(CURRENT_TIMESTAMP, '9', '5'),
(CURRENT_TIMESTAMP, '9', '6'),
(CURRENT_TIMESTAMP, '9', '7'),
(CURRENT_TIMESTAMP, '9', '8'),
(CURRENT_TIMESTAMP, '9', '9'),
(CURRENT_TIMESTAMP, '9', '10');
INSERT INTO `portage`(`creation_time`, `game_systemId`, `universeId`) VALUES (CURRENT_TIMESTAMP, '10', '1'),
(CURRENT_TIMESTAMP, '10', '2'),
(CURRENT_TIMESTAMP, '10', '3'),
(CURRENT_TIMESTAMP, '10', '4'),
(CURRENT_TIMESTAMP, '10', '5'),
(CURRENT_TIMESTAMP, '10', '6'),
(CURRENT_TIMESTAMP, '10', '7'),
(CURRENT_TIMESTAMP, '10', '8'),
(CURRENT_TIMESTAMP, '10', '9'),
(CURRENT_TIMESTAMP, '10', '10');
INSERT INTO `persona_type` (`name`, `universeId`) VALUES ('Class 1', '1'),
('Class 2', '1'),
('Class 3', '1'),
('Class 4', '1'),
('Class 5', '1');
INSERT INTO `persona_type` (`name`, `universeId`) VALUES ('Class 1', '2'),
('Class 2', '2'),
('Class 3', '2'),
('Class 4', '2'),
('Class 5', '2');
INSERT INTO `persona_type` (`name`, `universeId`) VALUES ('Class 1', '3'),
  ('Class 2', '3'),
  ('Class 3', '3'),
  ('Class 4', '3'),
  ('Class 5', '3');
INSERT INTO `persona_type` (`name`, `universeId`) VALUES ('Class 1', '4'),
  ('Class 2', '4'),
  ('Class 3', '4'),
  ('Class 4', '4'),
  ('Class 5', '4');
INSERT INTO `persona_type` (`name`, `universeId`) VALUES ('Class 1', '5'),
  ('Class 2', '5'),
  ('Class 3', '5'),
  ('Class 4', '5'),
  ('Class 5', '5');
INSERT INTO `persona_type` (`name`, `universeId`) VALUES ('Class 1', '6'),
  ('Class 2', '6'),
  ('Class 3', '6'),
  ('Class 4', '6'),
  ('Class 5', '6');
INSERT INTO `persona_type` (`name`, `universeId`) VALUES ('Class 1', '7'),
  ('Class 2', '7'),
  ('Class 3', '7'),
  ('Class 4', '7'),
  ('Class 5', '7');
INSERT INTO `persona_type` (`name`, `universeId`) VALUES ('Class 1', '8'),
  ('Class 2', '8'),
  ('Class 3', '8'),
  ('Class 4', '8'),
  ('Class 5', '8');
INSERT INTO `persona_type` (`name`, `universeId`) VALUES ('Class 1', '9'),
  ('Class 2', '9'),
  ('Class 3', '9'),
  ('Class 4', '9'),
  ('Class 5', '9');
INSERT INTO `persona_type` (`name`, `universeId`) VALUES ('Class 1', '10'),
  ('Class 2', '10'),
  ('Class 3', '10'),
  ('Class 4', '10'),
  ('Class 5', '10');